siteName: Arragon Affiliates
title: Arragon Affiliates
author: David White
url: https://github.com/webdigga/arragon-affiliates
description: Websites build by Arragon Affiliates
type: website
logoAlt: Arragon Affiliates logo
logoUrl: /static/img/logo.png
poweredBy: Arragon Affiliates is part of Arragon Digital Ltd.
registeredAddress: 57a Broadway, Leigh-On-Sea, Essex, United Kingdom, SS9 1PE
website: www.arragondigital.com
companyNumber: "10359530"
