siteName: Arragon Affiliates
title: Arragon Affiliates
author: David White
url: https://github.com/webdigga/arragon-affiliates
poweredBy: Arragon Affiliates
description: Websites build by Arragon Affiliates
type: website
logoAlt: Divorce Coach Logo, image of a leaf
logoUrl: /static/img/logo.png
